In [1]:
#Imports
import pandas as pd

In [2]:
file_path = "weather-anomalies-1964-2013.csv"
df = pd.read_csv(file_path)
df.head(10)

,date_str,degrees_from_mean,id,longitude,latitude,max_temp,min_temp,station_name,type,serialid
0,1977-02-19,8.61,USC00103882,-113.5472,43.7186,10.0,-12.8,GROUSE,Weak Hot,1
1,1977-02-19,10.74,USC00053951,-107.1097,37.7717,11.1,-8.9,HERMIT 7 ESE,Weak Hot,2
2,1977-02-19,20.46,USC00040379,-119.5128,37.0919,25.6,12.8,AUBERRY 2 NW,Strong Hot,3
3,1977-02-19,8.60,USC00020808,-109.7517,33.4783,20.0,-3.9,BLACK RIVER PUMPS,Weak Hot,4
4,1977-02-19,10.30,USC00042598,-115.4508,33.8089,30.6,13.9,EAGLE MTN,Weak Hot,5
5,1977-02-19,9.72,USW00024233,-122.3139,47.4444,19.4,3.3,SEATTLE TACOMA INTL AP,Weak Hot,6
6,1977-02-19,10.68,USC00267175,-114.9911,39.2764,15.6,-11.7,RUTH,Weak Hot,7
7,1977-02-19,10.41,USW00025507,-151.4908,59.6419,6.1,3.3,HOMER AP,Weak Hot,8
8,1977-02-19,7.66,USC00042294,-121.7761,38.5350,23.3,2.8,DAVIS 2 WSW EXP FARM,Weak Hot,9
9,1977-02-19,10.25,USC00105685,-113.8953,44.5664,13.9,-9.4,MAY 2SSE,Weak Hot,10